models:
  - name: stg__bike_data
    description: ""
    columns:
      - name: started_at_ts
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: ended_at_ts
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: tripduration
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: int

      - name: start_station_id
        description: ""

      - name: start_station_name
        description: ""

      - name: start_lat
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: start_lng
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: end_station_id
        description: ""

      - name: end_station_name
        description: ""

      - name: end_lat
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: end_lng
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: filename
        description: ""

  - name: stg__central_park_weather
    description: ""
    columns:
      - name: station
        description: ""

      - name: name
        description: ""

      - name: date
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date

      - name: awnd
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: prcp
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: snow
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: snwd
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: tmax
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: int

      - name: tmin
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: int

      - name: filename
        description: ""

  - name: stg__fhv_bases
    description: ""
    columns:
      - name: base_number
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist

      - name: base_name
        description: ""

      - name: dba
        description: ""

      - name: dba_category
        description: ""

      - name: filename
        description: ""

  - name: stg__fhv_tripdata
    description: ""
    columns:
      - name: dispatching_base_num
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - relationships:
                  to: source('main', 'fhv_bases')
                  field: base_number

      - name: pickup_datetime
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: dropoff_datetime
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: pulocationid
        description: ""

      - name: dolocationid
        description: ""

      - name: affiliated_base_number
        description: ""

      - name: filename
        description: ""

  - name: stg__fhvhv_tripdata
    description: ""
    columns:
      - name: hvfhs_license_num
        description: ""

      - name: dispatching_base_num
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - relationships:
                  to: source('main', 'fhv_bases')
                  field: base_number

      - name: originating_base_num
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - relationships:
                  to: source('main', 'fhv_bases')
                  field: base_number

      - name: request_datetime
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: on_scene_datetime
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: pickup_datetime
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: dropoff_datetime
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: pulocationid
        description: ""

      - name: dolocationid
        description: ""

      - name: trip_miles
        description: ""

      - name: trip_time
        description: ""

      - name: base_passenger_fare
        description: ""

      - name: tolls
        description: ""

      - name: bcf
        description: ""

      - name: sales_tax
        description: ""

      - name: congestion_surcharge
        description: ""

      - name: airport_fee
        description: ""

      - name: tips
        description: ""

      - name: driver_pay
        description: ""

      - name: shared_request_flag
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bool

      - name: shared_match_flag
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bool

      - name: access_a_ride_flag
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bool

      - name: wav_request_flag
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bool

      - name: wav_match_flag
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bool

      - name: filename
        description: ""

  - name: stg__green_tripdata
    description: ""
    columns:
      - name: vendorid
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist

      - name: lpep_pickup_datetime
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: lpep_dropoff_datetime
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: store_and_fwd_flag
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bool

      - name: ratecodeid
        description: ""

      - name: pulocationid
        description: ""

      - name: dolocationid
        description: ""

      - name: passenger_count
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: int

      - name: trip_distance
        description: ""

      - name: fare_amount
        description: ""

      - name: extra
        description: ""

      - name: mta_tax
        description: ""

      - name: tip_amount
        description: ""

      - name: tolls_amount
        description: ""

      - name: improvement_surcharge
        description: ""

      - name: total_amount
        description: ""

      - name: payment_type
        description: ""

      - name: trip_type
        description: ""

      - name: congestion_surcharge
        description: ""

      - name: filename
        description: ""

  - name: stg__yellow_tripdata
    description: ""
    columns:
      - name: vendorid
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist

      - name: tpep_pickup_datetime
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: tpep_dropoff_datetime
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: passenger_count
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: int

      - name: trip_distance
        description: ""

      - name: ratecodeid
        description: ""

      - name: store_and_fwd_flag
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bool

      - name: pulocationid
        description: ""

      - name: dolocationid
        description: ""

      - name: payment_type
        description: ""

      - name: fare_amount
        description: ""

      - name: extra
        description: ""

      - name: mta_tax
        description: ""

      - name: tip_amount
        description: ""

      - name: tolls_amount
        description: ""

      - name: improvement_surcharge
        description: ""

      - name: total_amount
        description: ""

      - name: congestion_surcharge
        description: ""

      - name: airport_fee
        description: ""

      - name: filename
        description: ""